### PR TITLE
Modify command

### PR DESCRIPTION
**Pull request by jakuboskera**
"kubectl create deploy nginx --image=nginx:1.7.8 --replicas=2 --port=80" does not work

### CODE REVIEW

**Comment by dgkanatsios** [comment]
this works on kubectl 1.19.2. What version are you using?

**Comment by fedkor** [comment]
kubectl and API server 1.17

**Comment by dgkanatsios** [comment]
want to try with 1.19 and let me know if you still see the issue?

**Comment by shubhamrajvanshi** [comment]
> kubectl and API server 1.17

While your change is valid for version 1.17, Kubernetes authors have separated the creation of deployment functionality to the verb ***create*** instead of run. So this may work on your local environment/machine but might fail during certification.

**Pull request closed without merging**
