### PR TITLE
Fix describe po annotation

### PR DESCRIPTION
**Pull request by DanyC97**

### CODE REVIEW

**Comment by dgkanatsios** [comment]
Thanks for that!
If I may ask, isn't the `grep` solution working for you? The JSONPath way is definitely more clear but (for me at least) it's a bit difficult to remember, compared to the `grep` solution. Worst case scenario, I think we should provide both solutions. What do you think?

**Comment by DanyC97** [comment]
sure it works, i only tried to be more "kubectl"-ish ;)

 i can add a note about jsonPath if that is okay ?

**Comment by dgkanatsios** [comment]
> sure it works, i only tried to be more "kubectl"-ish ;)
i can add a note about jsonPath if that is okay ?

Yeah, I understand, however I think it's difficult to do JSONPath during the 2-hour exam :) You can definitely insert a note, thanks!

**Comment by DanyC97** [comment]
does this work for you @dgkanatsios  ? if not please close it, you have a valid point during the exam though !

**Comment by dgkanatsios** [comment]
LGTM, thanks!

**Comment by DanyC97** [comment]
thank you for accepting contribution and for the great work you've done

**Pull request merged**
