### PR TITLE
fix cp issue in kubectl version 14

### PR DESCRIPTION
**Pull request by baogang**
For the question: Create a busybox pod with 'sleep 3600' as arguments. Copy '/etc/passwd' from the pod to your local folder

I got an error 'tar: removing leading '/' from member names', I used command 
`kubectl cp busybox:etc/passwd .` could work

kubectl version is
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}`

### CODE REVIEW

**Comment by dgkanatsios** [comment]
Thanks for the contribution! 
Pinging @8398a7 who also had an issue with this. Wondering why the leading ‘/‘ is an issue

**Comment by 8398a7** [comment]
Even when I tried it, the sentence itself was out, but I did not care because the copy was done correctly.
When you look at the document, it seems that the first / is necessary, but I think that you can remove it if it is deleted and it works properly. 
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands
If possible, you may try to issue an issue on k8s.

**Comment by baogang** [comment]
Yes, I tested again, even there is the error, the copy was done successfully, so we can close this. Thanks

**Comment by dgkanatsios** [comment]
Thanks both, added a comment line that describes the situation, let me know what you think

```
# previous command might report an error, feel free to ignore it since copy command works
```

**Pull request closed without merging**
