### PR TITLE
add base helm section (part of new CKAD syllabus)

### PR DESCRIPTION
**Pull request by moabukar**

### CODE REVIEW

**Comment by moabukar** [comment]
Added Helm section. Helm is currently part of the new syallbus. We can keep adding to this. Use this template as a base.

Thanks

**Review by MarcoPalomo — COMMENTED** [review]
Great. Just add the **helm repo** part

**Comment by moabukar** [comment]
> Great. Just add the **helm repo** part

ive added a part of helm repo. This is just a base, others can also add it in. @MarcoPalomo 

@dgkanatsios is this good with you ?

**Comment by dgkanatsios** [comment]
Sorry for the delay, merged!

**Comment by MarcoPalomo** [comment]
Nice !

**Comment by moabukar** [comment]
> Sorry for the delay, merged!

Nice, thanks!

**Pull request merged**
