### PR TITLE
Added more specifics to the question

### PR DESCRIPTION
**Pull request by parth-pandit**
The connection can be of various types. So, added the specifics.

### CODE REVIEW

**Comment by dgkanatsios** [comment]
kubectl exec is not SSH - https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

**Comment by dgkanatsios** [comment]
Coming back to this, I’d be more than happy to accept a change like “execute a simple shell on the nginx Pod”.
Thanks!

**Comment by parth-pandit** [comment]
This makes sense.

Regards,
Parth Pandit
Sr. Platform Architect - Pivotal Cloud Foundry
http://www.linkedin.com/in/parthpandit
Phone: +1 (470) 422-6629
________________________________

**Comment by dgkanatsios** [comment]
Feel free to amend this PR with the change, I’d be more than happy to accept it!

**Comment by parth-pandit** [comment]
I can’t find that pull request to update

Regards,
Parth Pandit
Sr. Platform Architect - Pivotal Cloud Foundry
http://www.linkedin.com/in/parthpandit
Phone: +1 (470) 422-6629
________________________________

**Comment by dgkanatsios** [comment]
I think this is it

https://github.com/parth-pandit/CKAD-exercises/tree/patch-2

**Comment by parth-pandit** [comment]
Done. Updated the patch-2 branch.

Regards,
Parth Pandit
Sr. Platform Architect - Pivotal Cloud Foundry
http://www.linkedin.com/in/parthpandit
Phone: +1 (470) 422-6629
________________________________

**Comment by dgkanatsios** [comment]
Awesome, thank you!

**Pull request merged**
