### PR TITLE
Exam Archives

### PR DESCRIPTION
**Pull request by rohit909**
Hi All,

the idea of this pull request is to add a section called exam-archives where the aspirants can find elaborate questions from CKAD exam experiences ( >= 5 points). added one question from my experience( the question is not exactly same but the procedure and idea is the same). 

let me know your thoughts on this.....

### CODE REVIEW

**Comment by dgkanatsios** [comment]
thanks @rohit909.
I'm pretty sure that sharing questions from the exam is against the [Linux Foundation Global Certification and Confidentiality Agreement](https://docs.linuxfoundation.org/tc-docs/certification/lf-cert-agreement)

**Comment by rohit909** [comment]
@dgkanatsios , the confidentiality agreement is not breached right, the question will be of similar model to what people have faced themselves and it will be like experience sharing. 

It will be a breach of contract if we try to save the questions in the duration of the exam i think.

**Comment by deepaksood619** [comment]
Question is to create `log-claim` pvc but answer has `log-volume-claim`.

**Comment by rohit909** [comment]
@dgkanatsios, didnt see any response from you. should i close the pr ?

**Comment by dgkanatsios** [comment]
hey, really sorry for the late response. Thanks for the PR, however I wouldn't like the repo to contain the same questions that exist in the exam. The spirit of this repo is to help candidates prepare for the exam and be more productive using kubectl. If you want to propose questions and answers to existing sections, I'd be more than welcome to accept them.  
Apologies for the inconvenience, happy to discuss more if needed.

**Pull request closed without merging**
